import type { Announcement, Club, EventItem } from "./types";

// ---------- Clubs ----------
export const clubs: Club[] = [
  {
    id: "aero",
    name: "Aero Society IARE",
    tagline: "Engineering the skies, one project at a time.",
    description:
      "The flagship aerospace club of IARE. We design and build RC aircraft, fixed-wing drones, rockets and run the institute's annual aeromodelling expo. Members get hands-on access to our fabrication lab, wind-tunnel test days and mentorship from alumni at DRDO and ISRO.",
    category: "Aerospace",
    members: 1240,
    founded: "2014",
    logo: "✈️",
    gradient: ["from-sky-500", "to-indigo-600"],
    officers: [
      { name: "Aditya Verma", role: "President", color: "from-sky-400 to-blue-600" },
      { name: "Sneha Reddy", role: "VP · Design", color: "from-fuchsia-400 to-purple-600" },
      { name: "Rahul Nair", role: "Technical Lead", color: "from-amber-400 to-orange-600" },
    ],
    achievements: [
      "1st place · National Aeromodelling Championship 2025",
      "Built & flew a 2.4m fixed-wing UAV with onboard telemetry",
      "Hosted 'SkyFiesta 2025' with 4,000+ attendees",
    ],
    socials: [
      { label: "Instagram", handle: "@aerosociety.iare" },
      { label: "LinkedIn", handle: "Aero Society IARE" },
    ],
  },
  {
    id: "codecraft",
    name: "CodeCraft Club",
    tagline: "Crafting the future, one commit at a time.",
    description:
      "The competitive programming & software development club. We run weekly problem-solving sessions, open-source projects, and bootcamps on full-stack, AI/ML and cloud. Our members consistently rank top in regional hackathons and ICPC regionals.",
    category: "Technical",
    members: 1890,
    founded: "2016",
    logo: "💻",
    gradient: ["from-emerald-500", "to-cyan-600"],
    officers: [
      { name: "Kiran Kumar", role: "President", color: "from-emerald-400 to-teal-600" },
      { name: "Ananya Sharma", role: "Events Head", color: "from-pink-400 to-rose-600" },
      { name: "Vikram Iyer", role: "Mentor", color: "from-indigo-400 to-violet-600" },
    ],
    achievements: [
      "Regional rank #3 · ICPC 2025",
      "Shipped 'CampusOS' — student portal used by 12,000+ students",
      "100+ members placed in product & engineering roles",
    ],
    socials: [
      { label: "GitHub", handle: "@codecraft-iare" },
      { label: "Discord", handle: "discord.gg/codecraft" },
    ],
  },
  {
    id: "dance",
    name: "Rhythmix Dance Crew",
    tagline: "Move like no one is watching.",
    description:
      "The official dance club of IARE — hip-hop, contemporary, bhangra and freestyle. We perform at every institute fest, college fests across the city, and train in our dedicated dance studio with professional choreographers.",
    category: "Cultural",
    members: 640,
    founded: "2012",
    logo: "🕺",
    gradient: ["from-pink-500", "to-rose-600"],
    officers: [
      { name: "Meera Joshi", role: "Captain", color: "from-pink-400 to-rose-600" },
      { name: "Arjun Rao", role: "Choreography Lead", color: "from-violet-400 to-purple-600" },
    ],
    achievements: [
      "Winners · 'Dance Dhamaka' inter-college 2025",
      "Performed at 20+ college fests across Hyderabad",
      "Featured in 'Young Dancers of India' showreel",
    ],
    socials: [{ label: "Instagram", handle: "@rhythmix.iare" }],
  },
  {
    id: "robo",
    name: "RoboX IARE",
    tagline: "Metal, code and adrenaline.",
    description:
      "Robotics lab club focused on combat bots, line-followers, and autonomous drones. We host buildathons, provide 3D-printing and PCB-fab access, and send teams to RoboWars and national robotics competitions.",
    category: "Robotics",
    members: 980,
    founded: "2017",
    logo: "🤖",
    gradient: ["from-orange-500", "to-red-600"],
    officers: [
      { name: "Pranav Shetty", role: "President", color: "from-orange-400 to-red-600" },
      { name: "Lakshmi Devi", role: "Build Lead", color: "from-cyan-400 to-blue-600" },
    ],
    achievements: [
      "Top 8 · National RoboWars 2025 (15kg class)",
      "Designed an autonomous warehouse bot for a smart-factory demo",
      "Hosted 'MechWar 6.0' with 60+ participating colleges",
    ],
    socials: [{ label: "YouTube", handle: "RoboX IARE" }],
  },
  {
    id: "music",
    name: "SwarAroha Music Club",
    tagline: "Where every note finds a home.",
    description:
      "Carnatic, Western, rock and EDM — SwarAroha is IARE's music society. Weekly jams, open-mic nights, a full-band setup, and vocal & instrumental training from visiting artists.",
    category: "Cultural",
    members: 720,
    founded: "2010",
    logo: "🎸",
    gradient: ["from-violet-500", "to-purple-700"],
    officers: [
      { name: "Ishita Banerjee", role: "President", color: "from-violet-400 to-purple-600" },
      { name: "Dev Anand", role: "Band Lead", color: "from-amber-400 to-yellow-600" },
    ],
    achievements: [
      "Headlined 'Campus Beats 2025' city tour",
      "Released 3 student-produced originals on streaming",
      "Orchestra for IARE's 25th Annual Day",
    ],
    socials: [{ label: "Instagram", handle: "@swararoha.iare" }],
  },
  {
    id: "sports",
    name: "IARE Athletics & Sports",
    tagline: "Play hard, win proud.",
    description:
      "The umbrella sports club covering cricket, football, basketball, badminton, athletics and e-sports. Organizes inter-branch leagues, fitness bootcamps and sends university teams to inter-college tournaments.",
    category: "Sports",
    members: 2150,
    founded: "2008",
    logo: "🏆",
    gradient: ["from-amber-500", "to-orange-600"],
    officers: [
      { name: "Rohit Menon", role: "Sports Secretary", color: "from-amber-400 to-orange-600" },
      { name: "Priya Sharma", role: "Cricket Captain", color: "from-green-400 to-emerald-600" },
    ],
    achievements: [
      "Inter-college cricket champions 2025",
      "5 medalists at state-level athletics meet",
      "Ran the first campus 'Midnight Marathon' with 1,200 runners",
    ],
    socials: [{ label: "Instagram", handle: "@iare_sports" }],
  },
  {
    id: "ecell",
    name: "E-Cell IARE",
    tagline: "Ideas in, startups out.",
    description:
      "The entrepreneurship cell of IARE. Runs incubation support, pitch competitions, founder talks and connects student startups with mentors, seed funding and the institute's innovation council.",
    category: "Entrepreneurship",
    members: 860,
    founded: "2019",
    logo: "🚀",
    gradient: ["from-cyan-500", "to-teal-600"],
    officers: [
      { name: "Nikhil Agarwal", role: "President", color: "from-cyan-400 to-teal-600" },
      { name: "Shreya Kulkarni", role: "Programs Lead", color: "from-fuchsia-400 to-pink-600" },
    ],
    achievements: [
      "3 student startups incubated with ₹5L seed fund",
      "Hosted 'PitchStorm 2025' — 120 teams, 40 judges",
      "Partnership with T-Hub, Hyderabad",
    ],
    socials: [{ label: "LinkedIn", handle: "E-Cell IARE" }],
  },
  {
    id: "drama",
    name: "Natak Theatre Society",
    tagline: "Life is a stage. We rehearse anyway.",
    description:
      "Street plays, stage drama, improv and short films. Natak is where IARE's storytellers, actors and directors find their crew. We produce one major play per semester plus a short-film festival.",
    category: "Cultural",
    members: 480,
    founded: "2015",
    logo: "🎭",
    gradient: ["from-fuchsia-500", "to-pink-600"],
    officers: [
      { name: "Aarav Singh", role: "Director", color: "from-fuchsia-400 to-pink-600" },
      { name: "Tanvi Desai", role: "Script Head", color: "from-indigo-400 to-blue-600" },
    ],
    achievements: [
      "Best Play · State Youth Theatre Fest 2025",
      "Short film 'Crossroads' screened at a city film festival",
      "Nukkad natak campaigns on campus awareness topics",
    ],
    socials: [{ label: "Instagram", handle: "@natak.iare" }],
  },
  {
    id: "photog",
    name: "Shutterbugs Photography",
    tagline: "Freeze the moment, frame the story.",
    description:
      "The photography & videography club. Covers every institute event, conducts lighting & editing workshops, and curates the annual campus photo exhibition.",
    category: "Cultural",
    members: 390,
    founded: "2016",
    logo: "📸",
    gradient: ["from-blue-500", "to-indigo-600"],
    officers: [
      { name: "Farhan Ali", role: "President", color: "from-blue-400 to-indigo-600" },
      { name: "Riya Kapoor", role: "Edit Lead", color: "from-rose-400 to-pink-600" },
    ],
    achievements: [
      "Official media partner for 'Vishwaksena 2025' fest",
      "Won 2 categories at inter-college photo contest",
      "Drone footage of campus featured in prospectus",
    ],
    socials: [{ label: "Instagram", handle: "@shutterbugs.iare" }],
  },
];

// ---------- Events ----------
const iso = (d: string) => `${d}T00:00:00`;

export const events: EventItem[] = [
  {
    id: "skyfiesta-2026",
    title: "SkyFiesta 2026 — Aero Expo & Air Show",
    clubId: "aero",
    category: "Aerospace",
    description:
      "IARE's biggest aerospace spectacle — RC air show, drone races, simulators and the annual aeromodelling expo.",
    longDescription: [
      "SkyFiesta is back, bigger than ever. Watch precision RC aerobatics teams battle for the sky, pilot racing drones through a neon obstacle course, and explore 60+ exhibits from student-built aircraft, rockets and UAVs.",
      "Hands-on zones include flight simulators, glider-building workshops for juniors, and a 'Design the Next Falcon' challenge with cash prizes. Food trucks, live DJ and a night laser show close the festival.",
      "Get your wristband at the Aero Lab or register here — spots are limited to 3,000.",
    ],
    date: iso("2026-08-28"),
    time: "9:00 AM – 8:00 PM",
    venue: "Main Grounds, IARE Campus",
    capacity: 3000,
    registrations: 2410,
    points: 100,
    tags: ["Airshow", "Expo", "Drones", "Fest"],
    gradient: ["from-sky-500", "to-indigo-600"],
    emoji: "✈️",
    isFeatured: true,
    prizes: "₹75,000 in prizes across 8 competitions",
  },
  {
    id: "hackverse-7",
    title: "HackVerse 7.0 — 36hr Hackathon",
    clubId: "codecraft",
    category: "Hackathon",
    description:
      "36 hours, real-world problem statements, ₹1L prize pool. Build with AI, cloud and hardware APIs.",
    longDescription: [
      "HackVerse 7.0 brings 400 hackers together for a sleepless 36 hours. Tracks include GenAI, Climate Tech, Health & EduTech, and Smart Campus. Mentors from industry (Microsoft, Swiggy, T-Hub) will be on the floor all weekend.",
      "Every team gets cloud credits, access to GPUs, and free meals + swag. Winners pitch to investors at the closing ceremony.",
      "Solo registrations allowed — we'll match you into a team during onboarding.",
    ],
    date: iso("2026-09-05"),
    time: "10:00 AM (starts) – Sun 10:00 PM",
    venue: "Innovation Block, IARE",
    capacity: 400,
    registrations: 352,
    points: 150,
    tags: ["Hackathon", "AI", "Cloud", "Prizes"],
    gradient: ["from-emerald-500", "to-cyan-600"],
    emoji: "💻",
    isFeatured: true,
    prizes: "₹1,00,000 prize pool + internship fast-tracks",
  },
  {
    id: "dance-riots",
    title: "Dance Riots — Inter-College Battle",
    clubId: "dance",
    category: "Cultural",
    description:
      "Collegiate dance crews battle for the crown in hip-hop, contemporary and bhangra categories.",
    longDescription: [
      "The city's most electric dance competition returns to IARE. 20+ crews from colleges across Hyderabad will battle in solo, duo and squad categories.",
      "Guest judges from the city's top dance academies. First prize includes a cash award and a music-video feature directed by a professional production house.",
      "Audience entry is free — come cheer and feel the bass.",
    ],
    date: iso("2026-09-12"),
    time: "5:00 PM – 10:00 PM",
    venue: "Open Air Auditorium",
    capacity: 1200,
    registrations: 934,
    points: 50,
    tags: ["Dance", "Battle", "Music"],
    gradient: ["from-pink-500", "to-rose-600"],
    emoji: "🕺",
    isFeatured: true,
    prizes: "₹50,000 + music video feature for winning crew",
  },
  {
    id: "robowars-7",
    title: "MechWar 7.0 — RoboWars Championship",
    clubId: "robo",
    category: "Robotics",
    description:
      "15kg and 30kg combat robots. Sparks, steel and glory in the arena.",
    longDescription: [
      "MechWar 7.0 opens registrations for combat bot teams nationwide. Three categories: 15kg, 30kg and a new autonomous mini-sumo league.",
      "The arena features a saw-blade hazard, flame pit and pulverizer. Pits open for teams from day one with engineering support from RoboX members.",
      "Spectators get a premium view, live commentary and on-screen damage telemetry.",
    ],
    date: iso("2026-09-26"),
    time: "10:00 AM – 7:00 PM",
    venue: "Sports Complex Arena",
    capacity: 1500,
    registrations: 812,
    points: 120,
    tags: ["Robotics", "Combat", "National"],
    gradient: ["from-orange-500", "to-red-600"],
    emoji: "🤖",
    prizes: "₹80,000 across weight classes",
  },
  {
    id: "ml-bootcamp",
    title: "GenAI & ML Bootcamp — Level Up",
    clubId: "codecraft",
    category: "Workshop",
    description:
      "Two-day hands-on bootcamp: LLMs, RAG, fine-tuning and building your first AI product.",
    longDescription: [
      "A practical, project-first bootcamp. Day 1 covers Python for ML, transformers and building RAG pipelines. Day 2 is fine-tuning, evaluation and deployment with a mini capstone.",
      "Bring your laptop. We provide cloud credits, notebooks and a certificate of completion + participation points.",
      "Open to all branches; prior coding basics recommended.",
    ],
    date: iso("2026-09-19"),
    time: "9:30 AM – 5:30 PM",
    venue: "Seminar Hall B, CS Block",
    capacity: 180,
    registrations: 146,
    points: 60,
    tags: ["AI", "ML", "Workshop", "Certificate"],
    gradient: ["from-teal-500", "to-emerald-600"],
    emoji: "🧠",
    prizes: "Certificates + cloud credits for all participants",
  },
  {
    id: "pitchstorm-2026",
    title: "PitchStorm 2026 — Startup Pitch Fest",
    clubId: "ecell",
    category: "Entrepreneurship",
    description:
      "Pitch your startup to VCs and win seed funding + incubation at T-Hub.",
    longDescription: [
      "PitchStorm is IARE's flagship startup competition. Apply with a 2-minute pitch video; the top 24 teams pitch live to a panel of founders, angel investors and T-Hub mentors.",
      "Winner takes seed funding, incubation and legal + design support. All finalists get investor feedback sessions.",
      "Attendee tickets include the founder keynotes and a networking mixer.",
    ],
    date: iso("2026-10-03"),
    time: "10:00 AM – 6:00 PM",
    venue: "Innovation Block Auditorium",
    capacity: 500,
    registrations: 210,
    points: 80,
    tags: ["Startup", "Funding", "Pitch"],
    gradient: ["from-cyan-500", "to-teal-600"],
    emoji: "🚀",
    isFeatured: true,
    prizes: "₹5,00,000 incubation package + seed cheque",
  },
  {
    id: "midnight-marathon",
    title: "Midnight Marathon 2.0",
    clubId: "sports",
    category: "Sports",
    description:
      "5K & 10K night run around the illuminated campus. Finisher medals, music zones and chai points.",
    longDescription: [
      "Lace up for the second edition of IARE's Midnight Marathon. Two distances (5K fun run / 10K timed), a fully illuminated route with music zones at every kilometer.",
      "Every finisher gets a medal, t-shirt and refreshment vouchers. Top-3 in each category win cash and gear from our sports partners.",
      "Entry includes a free fitness assessment camp the week before.",
    ],
    date: iso("2026-10-17"),
    time: "11:00 PM – 3:00 AM",
    venue: "Campus Loop — Main Gate to Block D",
    capacity: 1200,
    registrations: 870,
    points: 40,
    tags: ["Running", "Night", "Fitness"],
    gradient: ["from-amber-500", "to-orange-600"],
    emoji: "🏃",
    prizes: "Cash + sports gear for top finishers",
  },
  {
    id: "open-mic",
    title: "Open Mic Night — SwarAroha Sessions",
    clubId: "music",
    category: "Cultural",
    description:
      "Sing, slam or shred. An evening of acoustic sets, poetry and first-time performers.",
    longDescription: [
      "The monthly open mic returns with a special edition in the new amphitheatre. Sign up at the venue to perform — slots are first-come, first-served.",
      "House band kicks off the night, followed by 20+ acts: acoustic covers, originals, spoken word and more. Hot chocolate and cookies on the side.",
      "Free entry for all students.",
    ],
    date: iso("2026-08-21"),
    time: "6:30 PM – 9:30 PM",
    venue: "Amphitheatre, Near Main Library",
    capacity: 400,
    registrations: 180,
    points: 20,
    tags: ["Music", "Poetry", "Open Mic"],
    gradient: ["from-violet-500", "to-purple-700"],
    emoji: "🎸",
  },
  {
    id: "short-film-fest",
    title: "Reel It! — Short Film Festival",
    clubId: "drama",
    category: "Cultural",
    description:
      "48-hour filmmaking challenge + screening night with jury awards.",
    longDescription: [
      "Teams get a theme at 9 AM Friday and must deliver a 5-minute short by Sunday 9 AM. Cameras, actors, scripts — everything is fair game.",
      "All submissions screen on the big screen at the festival night, with jury awards for Best Film, Best Direction, Best Acting and Audience Choice.",
      "Borrow gear from the club's camera kit by registering early.",
    ],
    date: iso("2026-10-24"),
    time: "Screening 6:00 PM – 9:00 PM",
    venue: "Main Auditorium",
    capacity: 600,
    registrations: 245,
    points: 60,
    tags: ["Film", "Competition", "Creativity"],
    gradient: ["from-fuchsia-500", "to-pink-600"],
    emoji: "🎬",
    prizes: "₹30,000 in awards + film fest submissions",
  },
  {
    id: "drone-workshop",
    title: "Build Your Own FPV Drone",
    clubId: "aero",
    category: "Workshop",
    description:
      "Hands-on drone build workshop — frames, FCs, ESCs, tuning and your first flight.",
    longDescription: [
      "In this full-day workshop you'll assemble a 5-inch FPV drone from scratch: soldering the stack, flashing Betaflight, tuning PIDs and a supervised maiden flight in the drone cage.",
      "All components, tools and safety gear provided. You keep the drone (limited kit stock).",
      "Prerequisite: basic electronics interest. No experience needed.",
    ],
    date: iso("2026-09-13"),
    time: "8:30 AM – 5:00 PM",
    venue: "Aero Lab, Hangar B",
    capacity: 40,
    registrations: 34,
    points: 90,
    tags: ["Drones", "Hands-on", "FPV"],
    gradient: ["from-indigo-500", "to-sky-600"],
    emoji: "🛸",
    prizes: "Take home your custom-built FPV drone",
  },
  {
    id: "campus-cleanup",
    title: "Green Campus Drive",
    clubId: "photog",
    category: "Social",
    description:
      "Tree-planting, campus cleanup and a photo story contest on sustainability.",
    longDescription: [
      "A community day to make the campus greener. Teams take on cleanup zones, plant 500 saplings with the horticulture wing, and document the day as photo stories.",
      "Best photo story wins a camera accessory kit. Participation points for all volunteers.",
      "Breakfast, lunch and swag for volunteers.",
    ],
    date: iso("2026-08-16"),
    time: "7:00 AM – 12:00 PM",
    venue: "Campus — Meet at Main Gate",
    capacity: 300,
    registrations: 142,
    points: 30,
    tags: ["Volunteer", "Sustainability", "Photography"],
    gradient: ["from-green-500", "to-emerald-600"],
    emoji: "🌱",
  },
  {
    id: "guest-lecture-isro",
    title: "Evening with ISRO — Space Talk",
    clubId: "aero",
    category: "Seminar",
    description:
      "A special talk by a retired ISRO scientist on India's lunar missions and the future of spaceflight.",
    longDescription: [
      "An intimate evening session with a senior scientist from ISRO's Chandrayaan team. Hear first-hand stories from mission control, the engineering behind lunar landings, and what's next for Gaganyaan.",
      "Open Q&A for 45 minutes. Limited seating — register early.",
      "Students from all branches welcome.",
    ],
    date: iso("2026-10-09"),
    time: "5:00 PM – 7:00 PM",
    venue: "Main Auditorium",
    capacity: 800,
    registrations: 654,
    points: 50,
    tags: ["Space", "ISRO", "Talk"],
    gradient: ["from-blue-500", "to-indigo-700"],
    emoji: "🛰️",
    isFeatured: true,
  },
  {
    id: "badminton-open",
    title: "Badminton Open Championship",
    clubId: "sports",
    category: "Sports",
    description:
      "Singles, doubles and mixed doubles tournament across faculty & student categories.",
    longDescription: [
      "The annual badminton open with men's, women's and mixed doubles draws. Knockout format with seeding based on previous year results.",
      "Top players qualify for the university trials. Rackets available for hire at the venue.",
      "Registration closes 2 days before the event.",
    ],
    date: iso("2026-11-07"),
    time: "9:00 AM onwards",
    venue: "Indoor Sports Complex, Court 1–4",
    capacity: 128,
    registrations: 96,
    points: 25,
    tags: ["Badminton", "Tournament", "Sports"],
    gradient: ["from-lime-500", "to-emerald-600"],
    emoji: "🏸",
    prizes: "Trophies + sports kits for winners",
  },
  {
    id: "past-hackathon",
    title: "CodeSprint 1.0 (Completed)",
    clubId: "codecraft",
    category: "Hackathon",
    description:
      "Our 12-hour beginner-friendly sprint. Results & winners announced.",
    longDescription: [
      "A recap of CodeSprint 1.0: 300 participants, 60 teams, and some seriously impressive first-time builds. Gallery and winners available in the club's GitHub.",
    ],
    date: iso("2026-07-18"),
    time: "9:00 AM – 9:00 PM",
    venue: "Innovation Block",
    capacity: 300,
    registrations: 300,
    points: 0,
    tags: ["Hackathon", "Recap"],
    gradient: ["from-slate-500", "to-zinc-600"],
    emoji: "🏁",
  },
];

// ---------- Announcements ----------
export const announcements: Announcement[] = [
  {
    id: "ann-1",
    title: "🎉 SkyFiesta 2026 registrations are live!",
    body: "Wristbands for SkyFiesta are now open — first 3,000 get in. Air show, drone races, simulators and the night laser show. Register from the Events page before it fills up!",
    date: iso("2026-08-11"),
    priority: "urgent",
    author: "Aero Society IARE",
    clubId: "aero",
  },
  {
    id: "ann-2",
    title: "HackVerse 7.0 team matching opens today",
    body: "Register solo? We'll match you into a team at onboarding on Sep 5. Teams of 3–4 get priority seating. Cloud credits confirmed for all participants.",
    date: iso("2026-08-11"),
    priority: "important",
    author: "CodeCraft Club",
    clubId: "codecraft",
  },
  {
    id: "ann-3",
    title: "Club registration drive — Week 2",
    body: "Clubs are still accepting members for the 2026–27 cycle. Visit club stalls near the canteen every evening 5–7 PM, or join directly from club pages here.",
    date: iso("2026-08-10"),
    priority: "important",
    author: "Student Activities Council",
  },
  {
    id: "ann-4",
    title: "Midnight Marathon route announced",
    body: "The 5K and 10K routes now have music zones at every kilometer. Bib collection on Oct 16 at the Sports Complex from 4 PM.",
    date: iso("2026-08-09"),
    priority: "normal",
    author: "IARE Athletics & Sports",
    clubId: "sports",
  },
  {
    id: "ann-5",
    title: "Open Mic night — performer slots open",
    body: "Sign up at the amphitheatre from 5:30 PM on the day. 20 slots, first come first served. House gear available for acoustic sets.",
    date: iso("2026-08-08"),
    priority: "normal",
    author: "SwarAroha Music Club",
    clubId: "music",
  },
  {
    id: "ann-6",
    title: "ISRO talk — seating limited to 800",
    body: "The 'Evening with ISRO' talk is filling fast (654/800). It's on a first-register-first-seat basis, so book early.",
    date: iso("2026-08-07"),
    priority: "normal",
    author: "Aero Society IARE",
    clubId: "aero",
  },
];

// ---------- Helpers ----------
export const clubById = (id: string) => clubs.find((c) => c.id === id);
export const eventById = (id: string) => events.find((e) => e.id === id);
